version: "3"

networks:
  poll-api-private-subnet:
    ipam:
      config:
        - subnet: 172.16.0.0/16
    name: poll-api-private-subnet
  poll-api-public-subnet:
    ipam:
      config:
        - subnet: 172.32.0.0/16
    name: poll-api-public-subnet

services:
  grafana:
    attach: false
    container_name: grafana
    cpu_count: 1
    hostname: grafana
    image: grafana/grafana:11.0.0
    init: false
    mem_limit: 128mb
    mem_reservation: 0
    mem_swappiness: 0
    memswap_limit: 0
    networks:
      - poll-api-private-subnet
    restart: unless-stopped
    ports:
      - host_ip: 127.0.0.1
        protocol: tcp
        published: 3000
        target: 3000
    pull_policy: if_not_present
    stdin_open: false
    stop_grace_period: 60s
    stop_signal: SIGTERM
    tty: false
  mongodb:
    attach: false
    cap_drop: [ALL]
    container_name: mongodb
    cpu_count: 1
    hostname: mongodb
    image: mongo:7.0.11
    init: false
    mem_limit: 512mb
    mem_reservation: 0
    mem_swappiness: 0
    memswap_limit: 0
    networks:
      - poll-api-private-subnet
    restart: unless-stopped
    privileged: true
    pull_policy: if_not_present
    read_only: true
    stdin_open: false
    stop_grace_period: 60s
    stop_signal: SIGTERM
    tmpfs:
      - /tmp
    tty: false
  poll-api:
    attach: false
    cap_drop: [ALL]
    build:
      dockerfile: ./build/docker/Dockerfile
      tags:
        - poll-api:local
    command:
      - poll-api
      - --database-url=mongodb://mongodb:27017
    container_name: poll-api
    cpu_count: 1
    depends_on:
      - mongodb
    hostname: poll-api
    init: false
    mem_limit: 128mb
    mem_reservation: 0
    mem_swappiness: 0
    memswap_limit: 0
    networks:
      - poll-api-private-subnet
      - poll-api-public-subnet
    ports:
      - host_ip: 127.0.0.1
        protocol: tcp
        published: 80
        target: 80
    restart: unless-stopped
    privileged: false
    pull_policy: build
    read_only: true
    stdin_open: false
    stop_grace_period: 60s
    stop_signal: SIGTERM
    tty: false
  prometheus:
    attach: false
    cap_drop: [ALL]
    container_name: prometheus
    expose:
      - 9090
    cpu_count: 1
    hostname: prometheus
    image: prom/prometheus:v2.52.0
    init: false
    mem_limit: 128mb
    mem_reservation: 0
    mem_swappiness: 0
    memswap_limit: 0
    networks:
      - poll-api-private-subnet
    restart: always
    privileged: false
    pull_policy: if_not_present
    read_only: true
    stdin_open: false
    stop_grace_period: 60s
    stop_signal: SIGTERM
    tty: false
    volumes:
      - bind:
          create_host_path: false
          propagation: rshared
          selinux: Z
        read_only: false
        source: ./configs/prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        type: bind