name: Continuous Delivery

on:
  release:
    types: [released]

jobs:
  publish-to-ghcr:
    name: Publish to GitHub Container Registry
    if: ${{ github.repository_owner == 'yunusemre12500' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: yunusemre12500/multi-platform
          version: lab:latest

      - name: Extract Labels and Tags
        id: extract-metadata
        uses: docker/metadata-action@v5
        with:
          images: docker.io/yunusemre12500/poll-api-server
          tags: |
            type=raw,value={{sha}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/docker/Dockerfile
          push: true
          tags: ${{ steps.extract-metadata.outputs.tags }}
          labels: ${{ steps.extract-metadata.outputs.labels }}
