name: Continuous Delivery

on:
  release:
    types: [released]

jobs:
  publish-to-ghcr:
    name: Publish to GitHub Container Registry
    if: ${{ github.repository_owner == 'yunusemre12500' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Labels and Tags
        id: extract-metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=edge

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/docker/Dockerfile
          push: true
          tags: ${{ steps.extract-metadata.outputs.tags }}
          labels: ${{ steps.extract-metadata.outputs.labels }}
          platforms: |
            linux/amd64
            linux/arm64
            linux/ppc64le
            linux/s390x